language: zh

pipeline:
  - name: SpacyNLP
    model: "zh_core_web_md"
    case_sensitive: False
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
    pooling: mean
  - name: RegexFeaturizer
    case_sensitive: False
    use_word_boundaries: False
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 3000
    constrain_similarities: true
  - name: SpacyEntityExtractor
    dimensions: [GPE, DATE, PERSON]
  - name: RegexEntityExtractor
    case_sensitive: False
    use_lookup_tables: True
    use_regexes: True
    use_word_boundaries: False
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 1000
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.5
    ambiguity_threshold: 0.2

policies:
  - name: MemoizationPolicy
    max_history: 1
  - name: TEDPolicy
    max_history: 1
    epochs: 3000